import { EventEmitter } from '@angular/core';
import { Grid } from '../../lib/grid';
import { DataSource } from '../../lib/data-source/data-source';
export declare class Ng2SmartTableTbodyComponent {
    grid: Grid;
    source: DataSource;
    deleteConfirm: EventEmitter<any>;
    editConfirm: EventEmitter<any>;
    rowClassFunction: Function;
    save: EventEmitter<any>;
    cancel: EventEmitter<any>;
    edit: EventEmitter<any>;
    delete: EventEmitter<any>;
    custom1: EventEmitter<any>;
    custom2: EventEmitter<any>;
    custom3: EventEmitter<any>;
    custom4: EventEmitter<any>;
    custom5: EventEmitter<any>;
    custom6: EventEmitter<any>;
    custom7: EventEmitter<any>;
    custom: EventEmitter<any>;
    edited: EventEmitter<any>;
    userSelectRow: EventEmitter<any>;
    editRowSelect: EventEmitter<any>;
    multipleSelectRow: EventEmitter<any>;
    rowHover: EventEmitter<any>;
    isMultiSelectVisible: boolean;
    showActionColumnLeft: boolean;
    showActionColumnRight: boolean;
    mode: string;
    editInputClass: string;
    isActionAdd: boolean;
    isActionEdit: boolean;
    isActionDelete: boolean;
    isActionCustom1: boolean;
    isActionCustom2: boolean;
    isActionCustom3: boolean;
    isActionCustom4: boolean;
    isActionCustom5: boolean;
    isActionCustom6: boolean;
    isActionCustom7: boolean;
    noDataMessage: boolean;
    ngOnChanges(): void;
}
